language: node_js

node_js:
  - node # Stable
  - '--lts' # LTS: See https://github.com/creationix/nvm/pull/1070

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn build
  - yarn lint
  - yarn coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
