language: node_js

node_js:
  - node # Stable
  - '--lts' # LTS: See https://github.com/creationix/nvm/pull/1070

cache:
  yarn: true
  directories:
    - node_modules

script:
  - npm run lint
  - npm test
